/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutPagesImport } from './routes/_layout/_pages'
import { Route as LayoutlandingIndexImport } from './routes/_layout/(landing)/index'
import { Route as LayoutauthAuthImport } from './routes/_layout/(auth)/_auth'
import { Route as LayoutauthAuthSignUpSplatImport } from './routes/_layout/(auth)/_auth.sign-up.$'
import { Route as LayoutauthAuthSignInSplatImport } from './routes/_layout/(auth)/_auth.sign-in.$'

// Create Virtual Routes

const LayoutauthImport = createFileRoute('/_layout/(auth)')()

// Create/Update Routes

const LayoutauthRoute = LayoutauthImport.update({
  id: '/_layout/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPagesRoute = LayoutPagesImport.update({
  id: '/_layout/_pages',
  getParentRoute: () => rootRoute,
} as any)

const LayoutlandingIndexRoute = LayoutlandingIndexImport.update({
  id: '/_layout/(landing)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutauthAuthRoute = LayoutauthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutauthRoute,
} as any)

const LayoutauthAuthSignUpSplatRoute = LayoutauthAuthSignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => LayoutauthAuthRoute,
} as any)

const LayoutauthAuthSignInSplatRoute = LayoutauthAuthSignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => LayoutauthAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout/_pages': {
      id: '/_layout/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutPagesImport
      parentRoute: typeof rootRoute
    }
    '/_layout/(auth)': {
      id: '/_layout/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutauthImport
      parentRoute: typeof rootRoute
    }
    '/_layout/(auth)/_auth': {
      id: '/_layout/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutauthAuthImport
      parentRoute: typeof LayoutauthRoute
    }
    '/_layout/(landing)/': {
      id: '/_layout/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutlandingIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/(auth)/_auth/sign-in/$': {
      id: '/_layout/(auth)/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof LayoutauthAuthSignInSplatImport
      parentRoute: typeof LayoutauthAuthImport
    }
    '/_layout/(auth)/_auth/sign-up/$': {
      id: '/_layout/(auth)/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof LayoutauthAuthSignUpSplatImport
      parentRoute: typeof LayoutauthAuthImport
    }
  }
}

// Create and export the route tree

interface LayoutauthAuthRouteChildren {
  LayoutauthAuthSignInSplatRoute: typeof LayoutauthAuthSignInSplatRoute
  LayoutauthAuthSignUpSplatRoute: typeof LayoutauthAuthSignUpSplatRoute
}

const LayoutauthAuthRouteChildren: LayoutauthAuthRouteChildren = {
  LayoutauthAuthSignInSplatRoute: LayoutauthAuthSignInSplatRoute,
  LayoutauthAuthSignUpSplatRoute: LayoutauthAuthSignUpSplatRoute,
}

const LayoutauthAuthRouteWithChildren = LayoutauthAuthRoute._addFileChildren(
  LayoutauthAuthRouteChildren,
)

interface LayoutauthRouteChildren {
  LayoutauthAuthRoute: typeof LayoutauthAuthRouteWithChildren
}

const LayoutauthRouteChildren: LayoutauthRouteChildren = {
  LayoutauthAuthRoute: LayoutauthAuthRouteWithChildren,
}

const LayoutauthRouteWithChildren = LayoutauthRoute._addFileChildren(
  LayoutauthRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutPagesRoute
  '/': typeof LayoutlandingIndexRoute
  '/sign-in/$': typeof LayoutauthAuthSignInSplatRoute
  '/sign-up/$': typeof LayoutauthAuthSignUpSplatRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutPagesRoute
  '/': typeof LayoutlandingIndexRoute
  '/sign-in/$': typeof LayoutauthAuthSignInSplatRoute
  '/sign-up/$': typeof LayoutauthAuthSignUpSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout/_pages': typeof LayoutPagesRoute
  '/_layout/(auth)': typeof LayoutauthRouteWithChildren
  '/_layout/(auth)/_auth': typeof LayoutauthAuthRouteWithChildren
  '/_layout/(landing)/': typeof LayoutlandingIndexRoute
  '/_layout/(auth)/_auth/sign-in/$': typeof LayoutauthAuthSignInSplatRoute
  '/_layout/(auth)/_auth/sign-up/$': typeof LayoutauthAuthSignUpSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/sign-in/$' | '/sign-up/$'
  id:
    | '__root__'
    | '/_layout/_pages'
    | '/_layout/(auth)'
    | '/_layout/(auth)/_auth'
    | '/_layout/(landing)/'
    | '/_layout/(auth)/_auth/sign-in/$'
    | '/_layout/(auth)/_auth/sign-up/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutPagesRoute: typeof LayoutPagesRoute
  LayoutauthRoute: typeof LayoutauthRouteWithChildren
  LayoutlandingIndexRoute: typeof LayoutlandingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutPagesRoute: LayoutPagesRoute,
  LayoutauthRoute: LayoutauthRouteWithChildren,
  LayoutlandingIndexRoute: LayoutlandingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout/_pages",
        "/_layout/(auth)",
        "/_layout/(landing)/"
      ]
    },
    "/_layout/_pages": {
      "filePath": "_layout/_pages.tsx"
    },
    "/_layout/(auth)": {
      "filePath": "_layout/(auth)",
      "children": [
        "/_layout/(auth)/_auth"
      ]
    },
    "/_layout/(auth)/_auth": {
      "filePath": "_layout/(auth)/_auth.tsx",
      "parent": "/_layout/(auth)",
      "children": [
        "/_layout/(auth)/_auth/sign-in/$",
        "/_layout/(auth)/_auth/sign-up/$"
      ]
    },
    "/_layout/(landing)/": {
      "filePath": "_layout/(landing)/index.tsx"
    },
    "/_layout/(auth)/_auth/sign-in/$": {
      "filePath": "_layout/(auth)/_auth.sign-in.$.tsx",
      "parent": "/_layout/(auth)/_auth"
    },
    "/_layout/(auth)/_auth/sign-up/$": {
      "filePath": "_layout/(auth)/_auth.sign-up.$.tsx",
      "parent": "/_layout/(auth)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
