/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as authAuthSignUpSplatImport } from './routes/(auth)/_auth.sign-up.$'
import { Route as authAuthSignInSplatImport } from './routes/(auth)/_auth.sign-in.$'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const authAuthSignUpSplatRoute = authAuthSignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthSignInSplatRoute = authAuthSignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => authAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_auth/sign-in/$': {
      id: '/(auth)/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof authAuthSignInSplatImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/sign-up/$': {
      id: '/(auth)/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof authAuthSignUpSplatImport
      parentRoute: typeof authAuthImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthSignInSplatRoute: typeof authAuthSignInSplatRoute
  authAuthSignUpSplatRoute: typeof authAuthSignUpSplatRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthSignInSplatRoute: authAuthSignInSplatRoute,
  authAuthSignUpSplatRoute: authAuthSignUpSplatRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthRouteWithChildren
  '/sign-in/$': typeof authAuthSignInSplatRoute
  '/sign-up/$': typeof authAuthSignUpSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthRouteWithChildren
  '/sign-in/$': typeof authAuthSignInSplatRoute
  '/sign-up/$': typeof authAuthSignUpSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/_auth/sign-in/$': typeof authAuthSignInSplatRoute
  '/(auth)/_auth/sign-up/$': typeof authAuthSignUpSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in/$' | '/sign-up/$'
  id:
    | '__root__'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(auth)/_auth/sign-in/$'
    | '/(auth)/_auth/sign-up/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/sign-in/$",
        "/(auth)/_auth/sign-up/$"
      ]
    },
    "/(auth)/_auth/sign-in/$": {
      "filePath": "(auth)/_auth.sign-in.$.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/sign-up/$": {
      "filePath": "(auth)/_auth.sign-up.$.tsx",
      "parent": "/(auth)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
